import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { Swiper, SwiperSlide } from "swiper/react";
import "swiper/css";
// Components
import CardProduct from "../src/components/product/CardProduct.Components";
import { getCookie } from "cookies-next";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [topProductData, setTopProductData] = useState([]);

  useEffect(() => {
    TopProductApi();
  }, []);

  const TopProductApi = async () => {
    try {
      const TopProductApi = await (
        await axios.get(`api/product`, [])
      ).data.data;
      if (TopProductApi.length) {
        setTopProductData(TopProductApi);
      }
    } catch (error) {}
  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Swiper pagination={true} autoplay={{ delay: 1000 }}>
        <SwiperSlide>
          <div className={`slide-show`}>
            <div className={`card-slide-show`}>
              <img src="/test.jpg" className={`img`} alt="" />
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div className={`slide-show`}>
            <div className={`card-slide-show`}>
              <img src="/test.jpg" className={`img`} alt="" />
            </div>
          </div>
        </SwiperSlide>
        <SwiperSlide>
          <div className={`slide-show`}>
            <div className={`card-slide-show`}>
              <img src="/test.jpg" className={`img`} alt="" />
            </div>
          </div>
        </SwiperSlide>
      </Swiper>

      <div className={``}>
        <div className={`product-list-index`}>
          {topProductData.map((topProductList) => (
            <div key={topProductList.product_id}>
              <CardProduct
                product_id={topProductList.product_id}
                store_id={topProductList.store_id}
                product_name={topProductList.product_name}
                product_price={topProductList.product_price}
                product_rating={topProductList.product_rating}
              />
            </div>
          ))}
        </div>
      </div>
      <div className={`mt-[2rem]`}>
        <div className={`text-[25px] mb-[2rem]`}>Produk Rekomendasi</div>
        <div className={`product-list-index`}>
          <CardProduct></CardProduct>
        </div>
      </div>
    </>
  );
}
